$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  samplesheet:
    type: string
    description: path to sample-sheet TSV file

  transcriptome:
    type: string
    description: path to reference transcriptome directory

  localcores:
    type: number
    description: number of cores to use

  localmem:
    type: number
    description: amount of memory (in GB) to use

  runtime:
    type: string
    description: maximum runtime for each job (including units, e.g. "12h", "30m")

required:
  - samplesheet
  - transcriptome
  - localcores
  - localmem
  - runtime
