$schema: "https://json-schema.org/draft/2020-12/schema"
description: entries for the sample sheet
properties:
  sample_name:
    type: string
    description: sample name/identifier
  fastqs:
    type: string
    description: path to directory with FASTQ files for this sample

required:
  - sample_name
  - fastqs
